### PR TITLE
commit arm Dockerfile

### PR DESCRIPTION
**Pull request by jdamata**

### CODE REVIEW

**Comment by mdhiggins** [comment]
I have no arm devices on hand to test this on, have you tested this and on what devices?

**Comment by jdamata** [comment]
I have it working on a raspberry Pi 4, albeit with really slow speeds. I'm playing with different compiling options to see if I can speed up ffmpeg. 

I'll mark this as a draft while experimenting with compiling options

**Comment by mdhiggins** [comment]
Using this as a reference and some other material I was able to setup a github action and sepearte dockerfiles for armhf and arm64 which are now included in the latest/preview tags for Sonarr and latest/nightly tags for Radarr

image

Ended up just removing cryptography from the requirements since I don't believe its needed anymore and was just getting pulled in as part of the requests[security] bundle which allowed for a smaller image

Let me know if you encounter any issues

**Comment by jdamata** [comment]
Beauty!!! I tested out these images and they are working on the pi. IIRC the generated ffmpeg command used the copy codec which worked much faster. Thanks @mdhiggins

**Comment by mdhiggins** [comment]
Yeah if there's anything you can do to maximize how many streams are copied instead of encoded you'll improve your RPi performance significantly, especially if you can avoid encoding the video track

**Pull request closed without merging**
